// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj1ye5cF4lMrYQJkacxz8EMnCIIppMlA4',
    appId: '1:324979673403:web:00344c5ffc7894aea88f1e',
    messagingSenderId: '324979673403',
    projectId: 'vansale-3be8d',
    authDomain: 'vansale-3be8d.firebaseapp.com',
    storageBucket: 'vansale-3be8d.firebasestorage.app',
    measurementId: 'G-X1C1HP1WFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xHN6353N_bakRp3ZxcIecEzx0U8X_hw',
    appId: '1:324979673403:android:22e579c4b8a19030a88f1e',
    messagingSenderId: '324979673403',
    projectId: 'vansale-3be8d',
    storageBucket: 'vansale-3be8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHkQgj6cJCRAXIcyZU913l17j3qTA8UGU',
    appId: '1:324979673403:ios:6cb9e141fab24513a88f1e',
    messagingSenderId: '324979673403',
    projectId: 'vansale-3be8d',
    storageBucket: 'vansale-3be8d.firebasestorage.app',
    iosBundleId: 'com.odglao.odgcashvan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHkQgj6cJCRAXIcyZU913l17j3qTA8UGU',
    appId: '1:324979673403:ios:6cb9e141fab24513a88f1e',
    messagingSenderId: '324979673403',
    projectId: 'vansale-3be8d',
    storageBucket: 'vansale-3be8d.firebasestorage.app',
    iosBundleId: 'com.odglao.odgcashvan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEA9-qHL0OFbP9dnb5LrRn3UpoZdxTi6E',
    appId: '1:324979673403:web:c27f23689eff7a2ea88f1e',
    messagingSenderId: '324979673403',
    projectId: 'vansale-3be8d',
    authDomain: 'vansale-3be8d.firebaseapp.com',
    storageBucket: 'vansale-3be8d.firebasestorage.app',
    measurementId: 'G-JKRLGWFMJT',
  );
}
